repos:
  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        types: [file, python]
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # additional_dependencies: [flake8-docstrings]
        language_version: python3.8
        files: ^src/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
