[tool.black]
line-length = 100
include = '\.py$'

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
import_heading_stdlib = "Python Libraries"
import_heading_thirdparty = "Package Imports"
import_heading_firstparty = "First Party Imports"
import_heading_localfolder = "Local Imports"

[tool.check-manifest]
ignore = [
    "docs",
    "docs/**",
    "examples",
    "examples/**",
    ".gitignore",
    ".ipynb_checkpoints/*",
  ]
