[data_types]

[data_types.Net_Gen_By_Fuel_MWh]
fuels = ['all_sources', 'coal', 'natural_gas', 'nuclear', 'hydro', 'wind', 'solar_all', 'other']

[data_types.Fuel_Consumption_BTU]
fuels = ['coal', 'natural_gas']

[columns]
date = false # Name of date column, choose false to select it directly in the app.
target = false # Name of target column, choose false to select it directly in the app.
dimensions = false # List of dimension columns, choose false to select it directly in the app.
regressors = false # List of regressor columns, choose false to select it directly in the app.

[dataprep] # Default dataprep parameters
date_format = "%Y-%m-%d"
dimensions_agg = ["Mean", "Sum", "Min", "Max"] # List of possible target agg functions over dimensions. First is the default option.
remove_days = [] # List of days of week to remove from dataset.
# Select up to 6 elements among "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday".
remove_zeros = true # Whether or not to remove rows where target is 0 (true or false).
remove_negative = true # Whether or not to remove rows where target is <0 (true or false).
log_transform = false # Whether or not to apply a target log transform (true or false).


[tooltips]
app_page_choice = """
Use this dropdown to navigate between different app pages:
* __Single Region Analysis__: Analyze electricity generation and emissions for a single region (broken down by generation sources). Includes details for each time-forecasting model such as uncertainty in predictions, components that make up each prediction, etc.
* __Multi-Region Analysis__: Compare electricity generation and emissions across multiple regions for any generation source.
* __Emissions on USA Map__: Visualize emissions across all US states on a map at any point in time (both historical actuals and forecasted emissions).
"""
data_type_choice = """
There are two main types of Electricity Generation data explored in this analysis:
* __Net Electricity Generation (MWh)__: Represents the Net Electricity Generation in Megawatt Hours for different types of sources (coal, solar, etc.)
* __Electricity Fuel Consumption (BTU)__: This represents the amount of heat from the specified fuel used for electricty generation. This data type is only relevant for Coal and Natural Gas as it represents the amount of fuel used compared to renewable sources such as wind and solar where this is redundant.
__The default recommended option for almost all analysis is Net Electricity Generation (MWh).__
"""
show_all_sources_choice = """
Shows one curve each for different types of generation sources. \n
For example: Separate curves for Coal, Nuclear, Wind Generation, etc.
"""
time_unit_choice = """
__Note:__ The time-forecasting Prophet models were trained on __Quarterly__ time units.
Thus, expect wider uncertainty ranges when grouping the data by __Year__.
"""
multi_sources_choice = """
__Only available when 'Show Generation Sources Separately' is checked__.
"""
show_emissions_choice = """
__Only available when 'Show Generation Sources Separately' is checked__.

This option adds curves for the the Carbon Dioxide Equivalent Emissions for each of the chosen generation sources.

CO2 "Equivalent" emissions is a metric used to compare the emissions from various greenhouse gases on the basis of their global-warming potential (GWP). Basically, not every greenhouse gas contributes equally to global warming. \n
For example: Methane has a GWP of 25 which means that 1 kg of Methane is equivalent to 25 kg of Carbon Dioxide in the atmosphere.
"""
show_emissions_multi_region = """
This option adds curves for the the Carbon Dioxide Equivalent Emissions for each of the chosen regions / generation type.

CO2 "Equivalent" emissions is a metric used to compare the emissions from various greenhouse gases on the basis of their global-warming potential (GWP). Basically, not every greenhouse gas contributes equally to global warming. \n
For example: Methane has a GWP of 25 which means that 1 kg of Methane is equivalent to 25 kg of Carbon Dioxide in the atmosphere.
"""
emissions_type_choice = """
* __Emissions Intensity__: This is the volume of greenhouse gas emissions __per unit__ of electricity generated. Hence, the lower the emissions intensity, the greener the electricity grid. __This value allows for easier comparison of emissions between regions compared to using "Total Emissions".__
* __Total Emissions__: This is the volume of total greenhouse gas emissions for the chosen electricity generation source.
"""
source_choice_for_map = """
__Only available when 'Total Emissions' is chosen.__
"""











